/**
 */
package idm.bstrap.mm.bstrap.provider;

import idm.bstrap.mm.bstrap.util.BstrapAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class BstrapItemProviderAdapterFactory extends BstrapAdapterFactory
		implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public BstrapItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link idm.bstrap.mm.bstrap.Page} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PageItemProvider pageItemProvider;

	/**
	 * This creates an adapter for a {@link idm.bstrap.mm.bstrap.Page}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPageAdapter() {
		if (pageItemProvider == null) {
			pageItemProvider = new PageItemProvider(this);
		}

		return pageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link idm.bstrap.mm.bstrap.FixContainer} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FixContainerItemProvider fixContainerItemProvider;

	/**
	 * This creates an adapter for a {@link idm.bstrap.mm.bstrap.FixContainer}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFixContainerAdapter() {
		if (fixContainerItemProvider == null) {
			fixContainerItemProvider = new FixContainerItemProvider(this);
		}

		return fixContainerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link idm.bstrap.mm.bstrap.FluidContainer} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FluidContainerItemProvider fluidContainerItemProvider;

	/**
	 * This creates an adapter for a {@link idm.bstrap.mm.bstrap.FluidContainer}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFluidContainerAdapter() {
		if (fluidContainerItemProvider == null) {
			fluidContainerItemProvider = new FluidContainerItemProvider(this);
		}

		return fluidContainerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link idm.bstrap.mm.bstrap.Paragraphe} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ParagrapheItemProvider paragrapheItemProvider;

	/**
	 * This creates an adapter for a {@link idm.bstrap.mm.bstrap.Paragraphe}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createParagrapheAdapter() {
		if (paragrapheItemProvider == null) {
			paragrapheItemProvider = new ParagrapheItemProvider(this);
		}

		return paragrapheItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link idm.bstrap.mm.bstrap.Title} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TitleItemProvider titleItemProvider;

	/**
	 * This creates an adapter for a {@link idm.bstrap.mm.bstrap.Title}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTitleAdapter() {
		if (titleItemProvider == null) {
			titleItemProvider = new TitleItemProvider(this);
		}

		return titleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link idm.bstrap.mm.bstrap.Text} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TextItemProvider textItemProvider;

	/**
	 * This creates an adapter for a {@link idm.bstrap.mm.bstrap.Text}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTextAdapter() {
		if (textItemProvider == null) {
			textItemProvider = new TextItemProvider(this);
		}

		return textItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link idm.bstrap.mm.bstrap.Code} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CodeItemProvider codeItemProvider;

	/**
	 * This creates an adapter for a {@link idm.bstrap.mm.bstrap.Code}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCodeAdapter() {
		if (codeItemProvider == null) {
			codeItemProvider = new CodeItemProvider(this);
		}

		return codeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link idm.bstrap.mm.bstrap.Image} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ImageItemProvider imageItemProvider;

	/**
	 * This creates an adapter for a {@link idm.bstrap.mm.bstrap.Image}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createImageAdapter() {
		if (imageItemProvider == null) {
			imageItemProvider = new ImageItemProvider(this);
		}

		return imageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link idm.bstrap.mm.bstrap.Margin} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MarginItemProvider marginItemProvider;

	/**
	 * This creates an adapter for a {@link idm.bstrap.mm.bstrap.Margin}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMarginAdapter() {
		if (marginItemProvider == null) {
			marginItemProvider = new MarginItemProvider(this);
		}

		return marginItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link idm.bstrap.mm.bstrap.Padding} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PaddingItemProvider paddingItemProvider;

	/**
	 * This creates an adapter for a {@link idm.bstrap.mm.bstrap.Padding}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPaddingAdapter() {
		if (paddingItemProvider == null) {
			paddingItemProvider = new PaddingItemProvider(this);
		}

		return paddingItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link idm.bstrap.mm.bstrap.Background} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BackgroundItemProvider backgroundItemProvider;

	/**
	 * This creates an adapter for a {@link idm.bstrap.mm.bstrap.Background}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBackgroundAdapter() {
		if (backgroundItemProvider == null) {
			backgroundItemProvider = new BackgroundItemProvider(this);
		}

		return backgroundItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link idm.bstrap.mm.bstrap.Border} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BorderItemProvider borderItemProvider;

	/**
	 * This creates an adapter for a {@link idm.bstrap.mm.bstrap.Border}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBorderAdapter() {
		if (borderItemProvider == null) {
			borderItemProvider = new BorderItemProvider(this);
		}

		return borderItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link idm.bstrap.mm.bstrap.ColoredBorder} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ColoredBorderItemProvider coloredBorderItemProvider;

	/**
	 * This creates an adapter for a {@link idm.bstrap.mm.bstrap.ColoredBorder}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createColoredBorderAdapter() {
		if (coloredBorderItemProvider == null) {
			coloredBorderItemProvider = new ColoredBorderItemProvider(this);
		}

		return coloredBorderItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link idm.bstrap.mm.bstrap.Display1} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Display1ItemProvider display1ItemProvider;

	/**
	 * This creates an adapter for a {@link idm.bstrap.mm.bstrap.Display1}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDisplay1Adapter() {
		if (display1ItemProvider == null) {
			display1ItemProvider = new Display1ItemProvider(this);
		}

		return display1ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link idm.bstrap.mm.bstrap.Display2} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Display2ItemProvider display2ItemProvider;

	/**
	 * This creates an adapter for a {@link idm.bstrap.mm.bstrap.Display2}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDisplay2Adapter() {
		if (display2ItemProvider == null) {
			display2ItemProvider = new Display2ItemProvider(this);
		}

		return display2ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link idm.bstrap.mm.bstrap.Display3} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Display3ItemProvider display3ItemProvider;

	/**
	 * This creates an adapter for a {@link idm.bstrap.mm.bstrap.Display3}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDisplay3Adapter() {
		if (display3ItemProvider == null) {
			display3ItemProvider = new Display3ItemProvider(this);
		}

		return display3ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link idm.bstrap.mm.bstrap.Display4} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Display4ItemProvider display4ItemProvider;

	/**
	 * This creates an adapter for a {@link idm.bstrap.mm.bstrap.Display4}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDisplay4Adapter() {
		if (display4ItemProvider == null) {
			display4ItemProvider = new Display4ItemProvider(this);
		}

		return display4ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link idm.bstrap.mm.bstrap.Rounded} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RoundedItemProvider roundedItemProvider;

	/**
	 * This creates an adapter for a {@link idm.bstrap.mm.bstrap.Rounded}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRoundedAdapter() {
		if (roundedItemProvider == null) {
			roundedItemProvider = new RoundedItemProvider(this);
		}

		return roundedItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link idm.bstrap.mm.bstrap.Thumbnail} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ThumbnailItemProvider thumbnailItemProvider;

	/**
	 * This creates an adapter for a {@link idm.bstrap.mm.bstrap.Thumbnail}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createThumbnailAdapter() {
		if (thumbnailItemProvider == null) {
			thumbnailItemProvider = new ThumbnailItemProvider(this);
		}

		return thumbnailItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link idm.bstrap.mm.bstrap.Circle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CircleItemProvider circleItemProvider;

	/**
	 * This creates an adapter for a {@link idm.bstrap.mm.bstrap.Circle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCircleAdapter() {
		if (circleItemProvider == null) {
			circleItemProvider = new CircleItemProvider(this);
		}

		return circleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link idm.bstrap.mm.bstrap.Float} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FloatItemProvider floatItemProvider;

	/**
	 * This creates an adapter for a {@link idm.bstrap.mm.bstrap.Float}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFloatAdapter() {
		if (floatItemProvider == null) {
			floatItemProvider = new FloatItemProvider(this);
		}

		return floatItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link idm.bstrap.mm.bstrap.Center} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CenterItemProvider centerItemProvider;

	/**
	 * This creates an adapter for a {@link idm.bstrap.mm.bstrap.Center}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCenterAdapter() {
		if (centerItemProvider == null) {
			centerItemProvider = new CenterItemProvider(this);
		}

		return centerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link idm.bstrap.mm.bstrap.Responsive} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ResponsiveItemProvider responsiveItemProvider;

	/**
	 * This creates an adapter for a {@link idm.bstrap.mm.bstrap.Responsive}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createResponsiveAdapter() {
		if (responsiveItemProvider == null) {
			responsiveItemProvider = new ResponsiveItemProvider(this);
		}

		return responsiveItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link idm.bstrap.mm.bstrap.ButtonStyle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ButtonStyleItemProvider buttonStyleItemProvider;

	/**
	 * This creates an adapter for a {@link idm.bstrap.mm.bstrap.ButtonStyle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createButtonStyleAdapter() {
		if (buttonStyleItemProvider == null) {
			buttonStyleItemProvider = new ButtonStyleItemProvider(this);
		}

		return buttonStyleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link idm.bstrap.mm.bstrap.ButtonSize} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ButtonSizeItemProvider buttonSizeItemProvider;

	/**
	 * This creates an adapter for a {@link idm.bstrap.mm.bstrap.ButtonSize}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createButtonSizeAdapter() {
		if (buttonSizeItemProvider == null) {
			buttonSizeItemProvider = new ButtonSizeItemProvider(this);
		}

		return buttonSizeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link idm.bstrap.mm.bstrap.Link} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LinkItemProvider linkItemProvider;

	/**
	 * This creates an adapter for a {@link idm.bstrap.mm.bstrap.Link}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLinkAdapter() {
		if (linkItemProvider == null) {
			linkItemProvider = new LinkItemProvider(this);
		}

		return linkItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link idm.bstrap.mm.bstrap.Disabled} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DisabledItemProvider disabledItemProvider;

	/**
	 * This creates an adapter for a {@link idm.bstrap.mm.bstrap.Disabled}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDisabledAdapter() {
		if (disabledItemProvider == null) {
			disabledItemProvider = new DisabledItemProvider(this);
		}

		return disabledItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link idm.bstrap.mm.bstrap.Active} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ActiveItemProvider activeItemProvider;

	/**
	 * This creates an adapter for a {@link idm.bstrap.mm.bstrap.Active}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createActiveAdapter() {
		if (activeItemProvider == null) {
			activeItemProvider = new ActiveItemProvider(this);
		}

		return activeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link idm.bstrap.mm.bstrap.Button} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ButtonItemProvider buttonItemProvider;

	/**
	 * This creates an adapter for a {@link idm.bstrap.mm.bstrap.Button}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createButtonAdapter() {
		if (buttonItemProvider == null) {
			buttonItemProvider = new ButtonItemProvider(this);
		}

		return buttonItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>) type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (pageItemProvider != null)
			pageItemProvider.dispose();
		if (fixContainerItemProvider != null)
			fixContainerItemProvider.dispose();
		if (fluidContainerItemProvider != null)
			fluidContainerItemProvider.dispose();
		if (paragrapheItemProvider != null)
			paragrapheItemProvider.dispose();
		if (titleItemProvider != null)
			titleItemProvider.dispose();
		if (textItemProvider != null)
			textItemProvider.dispose();
		if (codeItemProvider != null)
			codeItemProvider.dispose();
		if (imageItemProvider != null)
			imageItemProvider.dispose();
		if (marginItemProvider != null)
			marginItemProvider.dispose();
		if (paddingItemProvider != null)
			paddingItemProvider.dispose();
		if (backgroundItemProvider != null)
			backgroundItemProvider.dispose();
		if (borderItemProvider != null)
			borderItemProvider.dispose();
		if (coloredBorderItemProvider != null)
			coloredBorderItemProvider.dispose();
		if (display1ItemProvider != null)
			display1ItemProvider.dispose();
		if (display2ItemProvider != null)
			display2ItemProvider.dispose();
		if (display3ItemProvider != null)
			display3ItemProvider.dispose();
		if (display4ItemProvider != null)
			display4ItemProvider.dispose();
		if (roundedItemProvider != null)
			roundedItemProvider.dispose();
		if (thumbnailItemProvider != null)
			thumbnailItemProvider.dispose();
		if (circleItemProvider != null)
			circleItemProvider.dispose();
		if (floatItemProvider != null)
			floatItemProvider.dispose();
		if (centerItemProvider != null)
			centerItemProvider.dispose();
		if (responsiveItemProvider != null)
			responsiveItemProvider.dispose();
		if (buttonStyleItemProvider != null)
			buttonStyleItemProvider.dispose();
		if (buttonSizeItemProvider != null)
			buttonSizeItemProvider.dispose();
		if (linkItemProvider != null)
			linkItemProvider.dispose();
		if (disabledItemProvider != null)
			disabledItemProvider.dispose();
		if (activeItemProvider != null)
			activeItemProvider.dispose();
		if (buttonItemProvider != null)
			buttonItemProvider.dispose();
	}

}
